Refactor GitHub Actions workflow for frun script
Removed the 'Extract Encoding Function' step and adjusted the verification step to issue a warning instead of exiting on failure.

diff --git a/.github/workflows/forkrun_release.yml b/.github/workflows/forkrun_release.yml
--- a/.github/workflows/forkrun_release.yml
+++ b/.github/workflows/forkrun_release.yml
@@ -184,9 +184,6 @@ jobs:
           find all_artifacts -name "*.so" -exec mv {} artifacts/ \;
           ls -l artifacts/
 
-      - name: Extract Encoding Function
-        run: |
-
       - name: Generate New frun Script
         shell: bash
         run: |
@@ -267,11 +264,12 @@ jobs:
           \rm encoder.sh
 
       - name: Verify Final Script
+        shell: bash
         run: |
           # Sanity check
           . ./frun.new.bash 
-          ring_version -a || exit 1
-          \rm -f ./frun.new.bash
+          ring_version -a || echo "WARNING: testing frun with new loadables failed!" >&2
+          \rm frun.new.bash
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v6
